### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by cjvanlissa** [xuan525/R128Normalization#1]
Dear @xuan525, I consistently receive the following error, and can't find the normalized files. Is the process failing? Thank you!

```
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Object.MemberwiseClone()
   at System.Array.Clone()
   at R128.Lufs.R128LufsMeter.ProcessBuffer(Double[][] buffer, Action`2 progressUpdated)
   at R128.Normalization.Normalize(Double[][] buffer, Double sampleRate)
   at R128.Normalization.Normalize(String inputFile, String outputFile)
```

**Comment by xuan25** [comment]
Hi Dr Caspar van Lissa, 

I thought it might be due to you are processing files with a long content duration. 

This program will load and store all the audio data and intermediate data into the memory, which require a significant of memory. Thus my solution is not a good practice. I initially wrote this for processing short audio files (around 4 mins), and it works in this case. Unfortunately, I might not have time to re-design the whole stuff to give it the ability to handle files of any length. I hope you can understand.

If you have more than 4GB of system memory and you compile the code with a 32-bit (or Any-CPU) configuration. I recommend that you compile the code with a 64-bit configuration. This lifts the software memory addressing restrictions to allow more memory to be used for the program. I hope this will help.

I also have two other potential solutions: either you can find a more professional solution instead of my one or slice your audio files into small sections, then process them separately. However, If you slice the audio, although the output should be similar, I cannot guarantee they are strict adherence to the R128 standard.

Best wishes,
Boxuan

**Comment by cjvanlissa** [comment]
Thank you for your quick response, Boxuan! I think this diagnosis is correct. As an alternative solution, I managed to do this with the ffmpeg extention `loudnorm`. All the best to you, 
Caspar
